### ISSUE TITLE
Package `solana-bpf-simplest v0.0.1` does not have these features: `program`

### ISSUE THREAD

**Issue by hritique** [mcf-rocks/simple-vote-tutorial#2]
Hi I was following the tutorial and building the simplest-rust package, then this error occured
Could you please explain the error and possible solution?

**Comment by mcf-rocks** [comment]
You are correct. Thank you for bringing this to my attention. I will fix within a couple of days.

**Comment by peerwaya** [comment]
Had similar issue. Can't make progress. Great tutorial!

**Comment by mcf-rocks** [comment]
Fixed.

[See it here](https://odysee.com/@MCF:0/Solana-Simple-Dapp-Tutorial-Deploy-Demo:2)
